# Site settings
github: https://github.com/710850609
github_username: 710850609
url: https://710850609.github.io
name: Less Or More
email: 710850609@qq.com
author: lin bo
resume_site: http://www.hifreud.com/Resume.io/
baseurl: ""
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


theme: jekyll-theme-cayman
